<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.web.capgemini.spring.altkom.pl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="HelloServiceImplService" targetNamespace="http://ws.web.capgemini.spring.altkom.pl/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.web.capgemini.spring.altkom.pl/" elementFormDefault="unqualified" targetNamespace="http://ws.web.capgemini.spring.altkom.pl/" version="1.0">

  <xs:element name="sayHallo" type="tns:sayHallo"/>

  <xs:element name="sayHalloResponse" type="tns:sayHalloResponse"/>

  <xs:complexType name="sayHallo">
    <xs:sequence>
      <xs:element minOccurs="0" name="name" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="sayHalloResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="sayHallo">
    <wsdl:part element="tns:sayHallo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="sayHalloResponse">
    <wsdl:part element="tns:sayHalloResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HelloService">
    <wsdl:operation name="sayHallo">
      <wsdl:input message="tns:sayHallo" name="sayHallo">
    </wsdl:input>
      <wsdl:output message="tns:sayHalloResponse" name="sayHalloResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HelloServiceImplServiceSoapBinding" type="tns:HelloService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHallo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="sayHallo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="sayHalloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HelloServiceImplService">
    <wsdl:port binding="tns:HelloServiceImplServiceSoapBinding" name="HelloServiceImplPort">
      <soap:address location="http://localhost:8084/spring-capgemini-web/services/HelloWorld"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>